name: Release Chrome Extension

on:
  push:
    tags:
      - 'v*'  # Trigger on tag push that starts with 'v'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        # Extract and store the tag from the GITHUB_REF environment variable.
        # This stores the tag value in the $tag environment variable.

      - name: Create ZIP file
        run: zip -r youtube-auto-commenter-extension.zip * -x "*.git*" "node_modules/*" ".github/*" "lib/*" ".*" "eslint.*"
        # Create a ZIP archive excluding unnecessary files and folders.

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: youtube-auto-commenter-extension.zip
          tag: ${{ github.ref }}
          name: Release ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
        # Use the ncipollo/release-action to create a GitHub release
        # using the generated ZIP file and the tag.
